use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Severity level for security alerts.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
pub enum AlertSeverity {
    /// Informational messages (VPN connected, rule added).
    Info,
    /// Medium severity (traffic blocked).
    Medium,
    /// High severity (VPN disconnect, DNS leak, module failure).
    High,
    /// Critical severity (ARP spoof, active attack).
    Critical,
}

impl std::fmt::Display for AlertSeverity {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            AlertSeverity::Info => write!(f, "INFO"),
            AlertSeverity::Medium => write!(f, "MEDIUM"),
            AlertSeverity::High => write!(f, "HIGH"),
            AlertSeverity::Critical => write!(f, "CRITICAL"),
        }
    }
}

/// Category of security alert.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum AlertCategory {
    /// VPN-related alerts.
    Vpn,
    /// Firewall-related alerts.
    Firewall,
    /// DNS-related alerts.
    Dns,
    /// ARP spoofing alerts.
    Arp,
    /// Module failure alerts.
    System,
    /// Other alerts.
    Other,
}

/// A security alert generated by the system.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Alert {
    /// Unique identifier for this alert.
    pub id: String,
    /// Severity level.
    pub severity: AlertSeverity,
    /// Alert category.
    pub category: AlertCategory,
    /// Short title of the alert.
    pub title: String,
    /// Detailed message.
    pub message: String,
    /// Timestamp when the alert was created.
    pub timestamp: chrono::DateTime<chrono::Utc>,
    /// Whether this alert has been acknowledged.
    pub acknowledged: bool,
}

impl Alert {
    /// Create a new alert with auto-generated ID and current timestamp.
    pub fn new(severity: AlertSeverity, title: String, message: String) -> Self {
        let category = match severity {
            AlertSeverity::Critical => AlertCategory::Arp,
            _ => AlertCategory::Other,
        };
        Self {
            id: Uuid::new_v4().to_string(),
            severity,
            category,
            title,
            message,
            timestamp: chrono::Utc::now(),
            acknowledged: false,
        }
    }

    /// Create an alert with explicit category.
    pub fn with_category(
        severity: AlertSeverity,
        category: AlertCategory,
        title: String,
        message: String,
    ) -> Self {
        Self {
            id: Uuid::new_v4().to_string(),
            severity,
            category,
            title,
            message,
            timestamp: chrono::Utc::now(),
            acknowledged: false,
        }
    }
}

impl std::fmt::Display for Alert {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "[{}] {} - {} ({})",
            self.severity, self.title, self.message, self.id
        )
    }
}

/// Configuration for the alert system.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AlertConfig {
    /// Whether the alert system is enabled.
    pub enabled: bool,
    /// Maximum number of alerts to keep in memory.
    pub max_alerts: usize,
    /// Minimum severity level to create alerts for.
    pub min_severity: AlertSeverity,
    /// Whether to log alerts to file.
    pub log_to_file: bool,
    /// Path to the alert log file.
    pub log_file_path: Option<String>,
    /// Maximum age for alerts before auto-cleanup (in seconds).
    pub max_age_secs: u64,
}

impl Default for AlertConfig {
    fn default() -> Self {
        Self {
            enabled: true,
            max_alerts: 1000,
            min_severity: AlertSeverity::Info,
            log_to_file: true,
            log_file_path: None,
            max_age_secs: 86400, // 24 hours
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_alert_severity_display() {
        assert_eq!(format!("{}", AlertSeverity::Info), "INFO");
        assert_eq!(format!("{}", AlertSeverity::Medium), "MEDIUM");
        assert_eq!(format!("{}", AlertSeverity::High), "HIGH");
        assert_eq!(format!("{}", AlertSeverity::Critical), "CRITICAL");
    }

    #[test]
    fn test_alert_severity_ordering() {
        assert!(AlertSeverity::Info < AlertSeverity::Medium);
        assert!(AlertSeverity::Medium < AlertSeverity::High);
        assert!(AlertSeverity::High < AlertSeverity::Critical);
    }

    #[test]
    fn test_alert_creation() {
        let alert = Alert::new(
            AlertSeverity::High,
            "Test".to_string(),
            "Message".to_string(),
        );

        assert!(!alert.id.is_empty());
        assert_eq!(alert.severity, AlertSeverity::High);
        assert_eq!(alert.title, "Test");
        assert_eq!(alert.message, "Message");
        assert!(!alert.acknowledged);
    }

    #[test]
    fn test_alert_with_category() {
        let alert = Alert::with_category(
            AlertSeverity::High,
            AlertCategory::Vpn,
            "VPN Alert".to_string(),
            "Disconnected".to_string(),
        );

        assert_eq!(alert.category, AlertCategory::Vpn);
    }

    #[test]
    fn test_alert_display() {
        let alert = Alert::new(
            AlertSeverity::Critical,
            "ARP Spoof".to_string(),
            "Detected attack".to_string(),
        );

        let display = format!("{}", alert);
        assert!(display.contains("CRITICAL"));
        assert!(display.contains("ARP Spoof"));
        assert!(display.contains("Detected attack"));
    }

    #[test]
    fn test_alert_serialization() {
        let alert = Alert::new(
            AlertSeverity::High,
            "Test".to_string(),
            "Message".to_string(),
        );

        let json = serde_json::to_string(&alert).unwrap();
        let deserialized: Alert = serde_json::from_str(&json).unwrap();

        assert_eq!(alert.id, deserialized.id);
        assert_eq!(alert.severity, deserialized.severity);
        assert_eq!(alert.title, deserialized.title);
    }

    #[test]
    fn test_alert_config_default() {
        let config = AlertConfig::default();
        assert!(config.enabled);
        assert_eq!(config.max_alerts, 1000);
        assert_eq!(config.min_severity, AlertSeverity::Info);
        assert!(config.log_to_file);
        assert_eq!(config.max_age_secs, 86400);
    }

    #[test]
    fn test_alert_config_serialization() {
        let config = AlertConfig {
            enabled: true,
            max_alerts: 500,
            min_severity: AlertSeverity::High,
            log_to_file: false,
            log_file_path: Some("/tmp/alerts.log".to_string()),
            max_age_secs: 3600,
        };

        let json = serde_json::to_string(&config).unwrap();
        let deserialized: AlertConfig = serde_json::from_str(&json).unwrap();

        assert_eq!(config.max_alerts, deserialized.max_alerts);
        assert_eq!(config.min_severity, deserialized.min_severity);
        assert_eq!(config.log_file_path, deserialized.log_file_path);
    }
}
